# Generated by Django 4.2.6 on 2024-02-15 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmploymentData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Series_reference', models.CharField(max_length=100)),
                ('Period', models.FloatField()),
                ('Data_value', models.CharField(max_length=100)),
                ('Suppressed', models.CharField(max_length=50)),
                ('Status', models.CharField(max_length=50)),
                ('Units', models.CharField(max_length=100)),
                ('Magnitude', models.CharField(max_length=100)),
                ('Subject', models.CharField(max_length=100)),
                ('Group', models.CharField(max_length=100)),
                ('Series_title_1', models.CharField(max_length=100)),
                ('Series_title_2', models.CharField(max_length=100)),
                ('Series_title_3', models.CharField(max_length=100)),
            ],
        ),
    ]
